name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [ 8, 8.0.192, 9.0.x, 10, 11.0.x, 11.0.3, 12, 13, 14 ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Compile
      run: sbt compile
    - name: Run tests
      run: sbt test
